Analyze_Blood_Test:
  description: >
    You will be analyzing the following blood test report:
    "{blood_report_text}"

    Instructions:
    1. Review each test result in the report.
    2. Identify the test name, the value, and the normal range.
    3. Compare the test value to the normal range:
      - If the value is within the normal range, note that it is normal.
      - If the value is outside the normal range, highlight it and explain the potential implications.
    4. Provide a comprehensive summary including:
      - An overview of all test results.
      - A detailed analysis of any abnormal values.
      - Potential implications of the abnormal results.
      - Suggestions for further investigation if needed.
  expected_output: >
    A comprehensive summary of the blood test results, highlighting abnormal values with explanations and potential implications.

search_health_articles_task:
  description: >
    Use an online search tool to find relevant health-related articles based on the findings and analysis provided by the "Analyze_Blood_Test" task. The goal is to gather information that can help the person improve or maintain their health.
  expected_output: >
    A list of health-related articles that are relevant to the analysis results, along with brief descriptions of each article.



generate_health_recommendations_task:
  description: >
    Provide health recommendations based on the articles found.
  expected_output: >
    Health recommendations with links to the articles..


send_email_task:
  description: >
    Compose and send an email to the user that includes the analysis of the blood test report, the health articles found, 
    and the personalized health recommendations. The goal is to deliver all the relevant information to the user in a 
    clear and concise manner.
  expected_output: >
    A confirmation that the email was successfully sent to the user, including the contents of the email.